### ISSUE TITLE
zip: android and store:true

### ISSUE THREAD

**Issue by ctalkington** [archiverjs/node-compress-commons#16]
```
java.util.zip.ZipException: unknown format (EXTSIG=6d783f3c)
E/Zip     (28060):  at java.util.zip.ZipInputStream.readAndVerifyDataDescriptor(ZipInputStream.java:196)
E/Zip     (28060):  at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:167)
E/Zip     (28060):  at org.apache.cordova.Zip.unzipSync(Zip.java:144)
E/Zip     (28060):  at org.apache.cordova.Zip.access$000(Zip.java:23)
E/Zip     (28060):  at org.apache.cordova.Zip$1.run(Zip.java:39)
E/Zip     (28060):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/Zip     (28060):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/Zip     (28060):  at java.lang.Thread.run(Thread.java:841)
```

moved from archiverjs/node-archiver#113

**Comment by ctalkington** [comment]
tracking this as it seems more related to this lib than archiver itself.

cc @mlegenhausen

**Comment by mlegenhausen** [comment]
Thanks for tracking this so long :) Would like to change back to a pure js based zip implementation.

**Comment by dwieeb** [comment]
Any news on this?

**Comment by ctalkington** [comment]
closing as i havent seen this in a bit. please open a new issue if you encounter issues.
