### ISSUE TITLE
TypeError: Cannot read property 'pipesCount' of undefined

### ISSUE THREAD

**Issue by NN---** [archiverjs/node-compress-commons#25]
Using Node 8 with gulp-zip the following error is arrives.
Unsure whether it is relevant for this project or for gulp.

```
TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)
    at module.exports.ZipArchiveOutputStream._smartStream (test\node_modules\compress-commons\lib\archivers\zip\zip-archive-output-stream.js:184:11)
    at module.exports.ZipArchiveOutputStream._appendStream (test\node_modules\compress-commons\lib\archivers\zip\zip-archive-output-stream.js:96:20)
    at module.exports.ArchiveOutputStream.entry (test\node_modules\compress-commons\lib\archivers\archive-output-stream.js:88:10)
    at module.exports.ZipStream.entry (test\node_modules\zip-stream\index.js:138:49)
    at Zip.append (test\node_modules\archiver\lib\plugins\zip.js:53:15)
    at Archiver._moduleAppend (test\node_modules\archiver\lib\core.js:172:16)
    at Archiver._onQueueTask (test\node_modules\archiver\lib\core.js:370:8)
    at test\node_modules\async\dist\async.js:4025:5
    at process (test\node_modules\async\dist\async.js:2332:17)
    at Immediate._onImmediate (test\node_modules\async\dist\async.js:2136:16)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

**Comment by dehimer** [comment]
Yes, I got this error too

**Comment by dehimer** [comment]
All problem in last changes of zlib library.
https://github.com/nodejs/node/pull/13370

**Comment by danielweck** [comment]
Yep, same error (NodeJS 8)
```
_stream_readable.js:545
  switch (state.pipesCount) {
               ^
TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)
    at module.exports.ZipArchiveOutputStream._smartStream (/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:184:11)
    at module.exports.ZipArchiveOutputStream._appendStream (/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:96:20)
    at module.exports.ArchiveOutputStream.entry (/node_modules/compress-commons/lib/archivers/archive-output-stream.js:88:10)
    at module.exports.ZipStream.entry (/node_modules/zip-stream/index.js:138:49)
    at Zip.append (/node_modules/archiver/lib/plugins/zip.js:53:15)
    at Archiver._moduleAppend (/node_modules/archiver/lib/core.js:172:16)
    at Archiver._onQueueTask (/node_modules/archiver/lib/core.js:370:8)
    at /node_modules/async/dist/async.js:3879:9
```

**Comment by franciscocpg** [comment]
Apparently it was solved on node 8.1.0. I haven't tested yet.
https://nodejs.org/en/blog/release/v8.1.0/
https://github.com/nodejs/node/pull/13374

**Comment by dehimer** [comment]
I tested. Now node-archiver again is works for me.

**Comment by NN---** [comment]
Confirm.
Node 8.1 with npm 5.0.3 everything works.
