### ISSUE TITLE
Deprecation warnings in Node 12

### ISSUE THREAD

**Issue by CliffReimers** [archiverjs/node-compress-commons#35]
This package has deprecation warnings in Node 12:

https://nodejs.org/api/deprecations.html#deprecations_dep0005_buffer_constructor

I could make a PR if that is wanted.

**Comment by CliffReimers** [comment]
I'm still getting warnings because the crc32-stream dependency is at 2.0.0.

**Comment by ctalkington** [comment]
hum tests dont seem to trigger the warning. I'll have to check again next chance I get.

**Comment by CliffReimers** [comment]
I don't get the warning on load anymore, only when using archiver. Stack trace for the warning:

(node:26492) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
     at showFlaggedDeprecation (buffer.js:154:11)
     at new Buffer (buffer.js:169:3)
    at new module.exports (webpack:///./node_modules/crc32-stream/lib/deflate-crc32-stream.js?:16:19)
     at module.exports.ZipArchiveOutputStream._smartStream (webpack:///./node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js?:167:27)
     at module.exports.ZipArchiveOutputStream._appendStream (webpack:///./node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js?:96:20)
     at module.exports.ArchiveOutputStream.entry (webpack:///./node_modules/compress-commons/lib/archivers/archive-output-stream.js?:88:10)
     at module.exports.ZipStream.entry (webpack:///./node_modules/zip-stream/index.js?:157:49)
     at Zip.append (webpack:///./node_modules/archiver/lib/plugins/zip.js?:54:15)
     at Archiver._moduleAppend (webpack:///./node_modules/archiver/lib/core.js?:178:16)
     at Archiver._onQueueTask (webpack:///./node_modules/archiver/lib/core.js?:397:8)

**Comment by ctalkington** [comment]
@CliffReimers can you confirm if the latest releases help here?
